export enum EnvVars {
    PULUMI_ACCESS_TOKEN = "PULUMI_ACCESS_TOKEN",
    PULUMI_STACK_NAME = "PULUMI_STACK_NAME",
    GITHUB_TOKEN = "GITHUB_TOKEN",
    ROLE_ARN = "ROLE_ARN",
    WHOAMI = "WHOAMI",
    PORT = "PORT",
    HOST = "HOST",
    MONGO_CONN_STRING = "MONGO_CLIENT_URL"
}