name: Deploy app
'on':
  push:
    branches:
      - mchaynes
permissions:
  id-token: write
  contents: read
env:
  MONGO_CLIENT_URL: ${{ secrets.MONGO_CLIENT_URL }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  WHOAMI: ${{ secrets.WHOAMI }}
  ROLE_ARN: ${{ secrets.ROLE_ARN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_STACK_NAME: ${{ secrets.PULUMI_STACK_NAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  update:
    environment: mchaynes
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: githubactions
          aws-region: us-west-2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: start app
        run: yarn && yarn run tsc && yarn node ./bin/index.js
        env:
          WHOAMI: ${{ secrets.WHOAMI }}
