name: Pulumi
'on':
  push:
    branches:
      - main
env: &ref_0
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - uses: pulumi/actions@v3
        env: *ref_0
        with:
          command: up
          stack-name: ${{ secrets.STACK_NAME }}
