name: Pulumi
'on':
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_STACK_NAME: ${{ secrets.PULUMI_STACK_NAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - uses: pulumi/actions@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_STACK_NAME: ${{ secrets.PULUMI_STACK_NAME }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
