name: Pulumi
'on':
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  ROLE_ARN: ${{ secrets.ROLE_ARN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_STACK_NAME: ${{ secrets.PULUMI_STACK_NAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: githubactions
          aws-region: us-west-2
      - name: Check permissions
        run: |
          aws sts get-caller-identity
      - uses: pulumi/actions@v3
        env:
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_STACK_NAME: ${{ secrets.PULUMI_STACK_NAME }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
